# Generated by Django 5.1.2 on 2025-04-27 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_aprendizaje', models.CharField(max_length=50)),
                ('programa', models.CharField(max_length=50)),
                ('apoyo_financiero', models.BooleanField(default=False)),
                ('condicion', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semestre', models.IntegerField()),
                ('numero_creditos', models.IntegerField()),
                ('horas_libres', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nota', models.FloatField()),
                ('porcentaje_evaluado', models.IntegerField()),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.semestre')),
            ],
        ),
    ]
