# Generated by Django 5.1.2 on 2025-04-27 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_remove_semestre_estudiante_delete_materia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semestre', models.IntegerField()),
                ('numero_creditos', models.IntegerField()),
                ('horas_libres', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nota', models.FloatField()),
                ('porcentaje_evaluado', models.IntegerField()),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userspace.semestre')),
            ],
        ),
    ]
