# Generated by Django 5.1.2 on 2025-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='creditos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
